### ISSUE TITLE
Add ability to empty recycle bin of service user

### ISSUE THREAD

**Issue by nathanpjones** [clearz/iTuneService#6]
If you're running iTunes as a non-admin user and then start it in interactive mode under that user to modify the library somehow and delete files, those files end up in the iTunes user's Recycle Bin.

There's a hacky way to do it [through the command line](http://lifehacker.com/5845698/force-recycle-bins-to-empty-for-every-user-on-a-system), but we should have an easy way to trigger a Recycle Bin empty.

**Comment by clearz** [comment]
Functionality like that would need to be put in either a top of the screen
menu
 or maybe a context menu when the user right clicks

**Comment by nathanpjones** [comment]
I put it next to the interactive mode button because that's when you'd be deleting and moving to recycle bin.

But I was thinking of the service user as a dedicated account. Maybe we could add an extra confirmation prompt if the service user is the same as the one running the service manager.

We should probably consider overhauling the UI, possibly in WPF which works great at designing UI around overarching program states. What are your thoughts?

**Comment by clearz** [comment]
WPF would be an improvement. Maybe we should split the code along the lines
of having a library for all non UI functionality and a WPF app for the
presentation?

**Comment by nathanpjones** [comment]
A split sounds like a good idea. There's certainly a fair bit that can be shared between the service and the service manager. This would allow to further simplify both.

I'll create a new issue so we can discuss further.
