### ISSUE TITLE
iTunes Home Sharing not working with iTuneService

### ISSUE THREAD

**Issue by artturnip** [clearz/iTuneService#9]
iTunes Home Sharing is not available when iTunes is launched through the service control "Start" button.

However launching it through the "Run iTunes Interactively" command launches iTunes with Home Sharing enabled.

**Comment by nathanpjones** [comment]
Thanks for reporting the issue! Sorry for taking so long to get back to you.

If you're still having trouble, please attach the logs found in: `%allusersprofile%\iTuneService`. For convenience, you may want to provide the files via a [gist](https://gist.github.com).

If you've resolved the problem on your own, please share your resolution and maybe we can make the app more robust.

**Comment by nathanpjones** [comment]
Closing because never got enough info to proceed.
